/*
	ShadowIRC - A Mac OS IRC Client
	Copyright (C) 1996-2000 John Bafford
	dshadow@shadowirc.com
	http://www.shadowirc.com

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*/

#define numProcs 286

#define procLSDelete 1
#define procLSCopy 2
#define procLSCopyString 3
#define procLSPosCustom 4
#define procLSPos 5
#define procLSPosChar 6
#define procLSNextArg 7
#define procLSNextArgND 8
#define procLSStrLS 9
#define procLSConcatLSAndStr 10
#define procLSConcatStrAndLS 11
#define procLSConcatStrAndStr 12
#define procLSConcatLSAndLS 13
#define procLSConcatLSAndStrAndLS 14
#define procLSConcatStrAndLSAndStr 15
#define procLSConcatStrAndStrAndStr 16
#define procLSStrCat 17
#define procLSInsertStr 18
#define procSMPrefix 19
#define procSMPrefixColor 20
#define procLineMsg 21
#define procUpdateStatusLine 22
#define procSetInputLineCursorSelection 23
#define procGetInputLine 24
#define procGetLine 25
#define procSetInputLine 26
#define procChannelMsg 27
#define procMessage 28
#define procNewPluginMWindow 29
#define procMWSetDimen 30
#define procMWSetFontSize 31
#define procMWDelete 32
#define procMWMessage 33
#define procDoModeLWindow 34
#define procEvtMW 35
#define procMWColor 36
#define procPluginNewDialog 37
#define procPluginDisposeDialog 38
#define procIsChannel 39
#define procIsDCCName 40
#define procMakeChannel 41
#define procChFind 42
#define procChFindBan 43
#define procChMatchBan 44
#define procChGetBan 45
#define procMWIrcleColor 46
#define procChKillBan 47
#define procChKillAllBans 48
#define procULAddUser 49
#define procULDeleteUser 50
#define procULFindUserName 51
#define procChannelWindow 52
#define procChMsg 53
#define procParamString 54
#define procSecsToHMS 55
#define procDeleteConnection 56
#define procFindConnectionSock 57
#define procCMAddSubmenu 58
#define procPluginNewConnection 59
#define procPutServer 60
#define procDoONotice 61
#define procSendCTCPReply 62
#define procPMLAdd 63
#define procNextArg 64
#define procHandleCommand 65
#define procWriteMainPrefs 66
#define procWriteAllFiles 67
#define procUlongval 68
#define procCMSetCheckmark 69
#define procUlongstr 70
#define procDccTypToStr 71
#define procDccFlagTypToStr 72
#define procDccStrToTyp 73
#define procHostToIPStr 74
#define procDCCFind 75
#define procDCCClose 76
#define procDCCWindowClose 77
#define procDCCCreate 78
#define procDCCRequest 79
#define procDCCOpen 80
#define procDCCCommand 81
#define procDCCSSay 82
#define procSendCommand 83
#define procDNSLookup 84
#define procDoBroadcast 85
#define procListIgnores 86
#define procIsIgnored 87
#define procDoIgnore 88
#define procFindIgnore 89
#define procProcessShortcutText 90
#define procMBIdle 91
#define procMBFindNick 92
#define procMBNewMessage 93
#define procUpc 94
#define procUcase 95
#define procPdelete 96
#define procPinsert 97
#define procPstrcpy 98
#define procPstrcmp 99
#define procExistsService 100
#define procStandardDialogFilter 101
#define procPadEnd 102
#define procPadBegin 103
#define procMaskMatch 104
#define procMakeMask 105
#define procCountChar 106
#define procRevPos 107
#define procIsNumber 108
#define procIsIPNumber 109
#define procGetText 110
#define procSetText 111
#define procSetCheckBox 112
#define procGetCheckBox 113
#define procSetButtonEnable 114
#define procGetControlHandle 115
#define procGetFirstSelectedCell 116
#define procSelectOneCell 117
#define procDrawListBorder 118
#define procMakeCellVisible 119
#define procOpenConnection 120
#define procDrawPlacard 121
#define procSetTextColor 122
#define procSetDlogFont 123
#define procGetControlMenu 124
#define procLSPosCase 125
#define procPos 126
#define procShadowIRCVersion 127
#define procPluginNewWindow 128
#define procPluginDisposeWindow 129
#define procNewService 130
#define procPFOpen 131
#define procPFExists 132
#define procPFCreate 133
#define procPFWrite 134
#define procPFRead 135
#define procPFSize 136
#define procPFResize 137
#define procPFSetPos 138
#define procPFClose 139
#define procPFDelete 140
#define procFrontNonFloater 141
#define procGetPluginWindowOwner 142
#define procWIsFloater 143
#define procWMoveToFront 144
#define procWSelect 145
#define procWDrag 146
#define procWShow 147
#define procWHide 148
#define procPstrcasecmp 149
#define procPstrcasecmp2 150
#define procGetQD 151
#define procWMove 152
#define procEnterModalDialog 153
#define procExitModalDialog 154
#define procLSConcatLSAndStrAndStr 155
#define procIPStringToLong 156
#define procSetSmartScrollInfo 157
#define procSetSmartScrollProp 158
#define procGetSmartScrollProp 159
#define procLCAttach 160
#define procLCDetach 161
#define procLCSetValue 162
#define procLCSetMin 163
#define procLCSetMax 164
#define procLCGetValue 165
#define procLCGetMin 166
#define procLCGetMax 167
#define procLCSynch 168
#define procIsChannelValid 169
#define procIsUserValid 170
#define procConnPut 171
#define procConnPutText 172
#define procConnPutLS 173
#define procStackModes 174
#define procOpenPreferencesWindow 175
#define procSMPrefixIrcleColor 176
#define procAsyncSoundPlay 177
#define procLSCmp 178
#define procLSCaseCmp 179
#define procLSGetIndString 180
#define procLSParamString 181
#define procLSParamLS 182
#define procSMLink 183
#define procSMPrefixLink 184
#define procSMPrefixLinkColor 185
#define procSMPrefixLinkIrcleColor 186
#define procIPCRegister 187
#define procIPCExists 188
#define procIPCCall 189
#define procDoNotify 190
#define procRunNotify 191
#define procListNotify 192
#define procfindNotify 193
#define procdeleteNotify 194
#define procaddNotify 195
#define procDrawMWinStatus 196
#define procConnClose 197
#define procConnAbort 198
#define procConnNewActive 199
#define procConnNewPassive 200
#define procConnGetData 201
#define procConnCharsAvail 202
#define procIWNewObject 203
#define procIWRecalculateRects 204
#define procIWPopUpMenu 205
#define procIWDeleteObject 206
#define procIWOverride 207
#define procMWNewWidget 208
#define procMWRecalculateRects 209
#define procMWDestroyWidget 210
#define procHMIAdd 211
#define procMWFindWidget 212
#define procMWFindPane 213
#define procMWNewPane 214
#define procMWPaneRecalculate 215
#define procMWPaneResize 216
#define procStartDrawingOffscreen 217
#define procEndDrawingOffscreen 218
#define procAbortDrawingOffscreen 219
#define procMWDestroyPane 220
#define procLSInsertChar 221
#define procLSInsertShort 222
#define procLSInsertLong 223
#define procLightenColor 224
#define procNavDialogFilter 225
#define procDirectorySelectButton 226
#define procCleanFolderFSp 227
#define procDoDCCSend 228
#define procDoDCCSendFile 229
#define procDCCGetAFile 230
#define procInputHandler 231
#define procOpenURL 232
#define procDCCTypeAdd 233
#define procDCCGetStatus 234
#define procProcessLine 235
#define procProcessInputHunk 236
#define procDragHilightRect 237
#define procDragHilightRectBG 238
#define procDragIsTypeAvail 239
#define procDragGetType 240
#define procDragGetPtr 241
#define procDragAddPtr 242
#define procDCCSendCookie 243
#define procDCCSendCookieReply 244
#define procCMAdd 245
#define procIPCReply 246
#define procLSPosCaseCustom 247
#define procSetBackground 248
#define procMySendControlMessage 249
#define procSMPrefixRGBColor 250
#define procSMPrefixRGBLinkColor 251
#define procpluginSetWRefCon 252
#define procpluginGetWRefCon 253
#define procMWPaneUpdate 254
#define procShadowIRCVersion2 255
#define procSetDlogItemTextHdl 256
#define procDrawBorder 257
#define procFileAdd 258
#define procFileClose 259
#define procIsIgnoredNickUser 260
#define procWMSGetMenuItemNum 261
#define procGetInputLineCursorSelection 262
#define procLockInput 263
#define procUnlockInput 264
#define procDoServer 265
#define procDoSignoff 266
#define procWMSListAdd 267
#define procILGetLine 268
#define procILSetLine 269
#define procMWGetName 270
#define procMWGetChannel 271
#define procMWGetDCC 272
#define procDoModeKWindow 273
#define procConnGetLocalPort 274
#define procRegisterAETE 275
#define procNickListAdd 276
#define procChannelListAdd 277
#define procGetDrawingState 278
#define procSetDrawingState 279
#define procNormalizeDrawingState 280
#define procGetAppearanceListBoxHandle 281
#define procCopyResource 282
#define procPstrcat 283
#define procMWPart 284
#define procWindowClose 285